[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Storage.path /fluent-bit/buffer
    Storage.sync normal
    Storage.checksum off
    Storage.backlog.mem_limit 10M

[INPUT]
    Name          mqtt
    Listen        0.0.0.0
    Port          1883
    Tag           fw.logs
    Storage.type  filesystem

[FILTER]
    Name    lua
    Match   fw.logs
    call    strip_log_prefix
    script  /fluent-bit/etc/strip_prefix.lua

[OUTPUT]
    Name          loki
    Match         fw.logs
    Host          loki
    Port          3100
    Labels        job=fw_debugging
    Label_Keys    $topic
    Line_Format   json
